### ISSUE TITLE
How to use this library to make two or more virtual webcams on Windows?

### ISSUE THREAD

**Issue by wukongxuetang** [tshino/softcam#11]
It gave an error when running sender example while I add other virtual webcam.
first is active  and second failed.

Ok, Softcam1 is now active.
failed to create camera2

![1662542580483](https://user-images.githubusercontent.com/18222945/188842697-bb44f31c-3206-4c25-b376-5c5fe9f77b66.png)

**Comment by tshino** [comment]
Thank you for your interest!
Unfortunately, this library can create only one virtual webcam.
Attempts to create a virtual webcam when another one already exists will fail.

It is not so easy thing to change this design because of the design of Windows.
In order to create multiple virtual webcams, we need to register multiple GUIDs (IDs for each webcam) to the system at installation.
And here we do only one:
https://github.com/tshino/softcam/blob/2b7abc80bbb966745dc55b754c211dfdb89d6947/src/softcam/softcam.cpp#L18-L21

But if we register multiple GUIDs, that is just a starting point of whole things we need to complete changing the design of this library.
Instead, I chose the simplest design for this library.

**Comment by wukongxuetang** [comment]
Thank you for your reply. It's very good to create only one virtual webcam. I hope this library has more functions.

**Comment by tshino** [comment]
Thank you!
