### ISSUE TITLE
Issues with the 32 bit support

### ISSUE THREAD

**Issue by mateberes** [tshino/softcam#38]
HI tsihon!

Great library, I have a project in unreal in which I integrated this library. The 64bit version works flawlessly, I can stream to Discord (from browser) or to Google Meet. But I've realized that the standalone version of discord is still 32bit, so I've tried to add support for as that well. 

But it just doesn't work and I'm not sure why. I can see the virtual camera option in the discord camera combobox and I checked the registry for the COM object and the path is correct. 
There might be some kind of race condition with the initialization, because sometimes 1 out of 10 it starts working if I attach my VS to both of my running instances and debug it step by step. (Unreal and Discord)

Do you have any idea what could go wrong? Because I have no issues with the 64bit version. And I could even manage to run the 32bit version, but only if I debug it in VS.

**Comment by tshino** [comment]
Thank you for a detailed report!

Based on your observation, I agree with your guess of a possible race condition.
And I agree that the call stacks are clearly indicating a deadlock!
Reading the code, the first thread gets a lock and waits for the second to respond, but simultaneously, the second attempts to get the lock.

I think the cause is not a 32-bit related.
I will investigate further.
Thank you!

**Comment by tshino** [comment]
Hi, @mateberes !
I think I have fixed the deadlock issue you spotted.
I hope the situation becomes better.
